INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (1, 6, 'email1', 'name1', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');
INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (2, 18, 'email2', 'name2', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');
INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (3, 20, 'email3', 'name3', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');

INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (1, 'RED', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (2, 'RED', 'text', 2);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (3, 'RED', 'text', 3);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (4, 'BLACK', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (5, 'BLACK', 'text', 2);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (6, 'BLACK', 'text', 3);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (7, 'WHITE', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (8, 'BLUE', 'text', 2);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (9, 'YELLOW', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (10, 'GREEN', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (11, 'BLUE', 'text', 3);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (12, 'BLUE', 'someText', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (13, 'GREEN', 'someText', 1);


