INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (1, 6, 'email1', 'name1', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');
INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (2, 18, 'email2', 'name2', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');
INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (3, 20, 'email3', 'name3', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');
INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (4, 10, 'email4', 'name4', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');
INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (5, 15, 'email5', 'name5', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');
INSERT INTO USERS (ID, AGE, EMAIL, FIRST_NAME, PASSWORD) VALUES (6, 35, 'email6', 'name6', '$2a$10$0uKlKXqZfBHLn68nrnoD8uwhXkf/BglGhMySgwUYmaEYh3PTsQL5q');

INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (1, 'RED', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (2, 'RED', 'text', 2);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (3, 'RED', 'text', 3);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (4, 'BLACK', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (5, 'BLACK', 'text', 2);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (6, 'BLACK', 'text', 3);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (7, 'WHITE', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (8, 'BLUE', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (9, 'YELLOW', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (10, 'GREEN', 'text', 1);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (11, 'BLUE', 'text', 3);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (12, 'BLUE', 'someText', 4);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (13, 'RED', 'someText', 5);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (14, 'GREEN', 'someText', 6);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (15, 'GREEN', 'someText', 5);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (16, 'YELLOW', 'someText', 6);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (17, 'GREEN', 'someText', 4);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (18, 'BLACK', 'someText', 3);
INSERT INTO ARTICLE (ID, COLOR, TEXT, FK_ARTICLE_ID) VALUES (19, 'YELLOW', 'someText', 4);


